language: php

php:
    - 5.4

before_script:
    - composer install --no-interaction --dev
    - wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.10.zip -nv
    - unzip -q google_appengine_1.9.10.zip
    - patch -p0 < tests/patches/sdk-expose-remote-api-settings.patch

script:
    - mkdir -p logs
    - bash -c './google_appengine/dev_appserver.py tests/ --php_executable_path=$HOME/.phpenv/versions/$(phpenv version-name)/bin/php-cgi --skip_sdk_update_check --php_remote_debugging=yes 1>logs/out.log 2>logs/err.log & echo $! > appengine.pid'
    - vendor/bin/phpunit --coverage-clover logs/build-clover.xml tests/

after_script:
    - bash -c 'cat appengine.pid | xargs kill'
    #never has anything interesting
    #- cat out.log
    - cat err.log
    - php vendor/bin/coveralls -v
