language: php

php:
    - 5.4

before_script:
    - composer install --no-interaction --dev
    - wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.10.zip -nv
    - unzip -q google_appengine_1.9.10.zip
    - bash -c './google_appengine/dev_appserver.py tests/ --php_executable_path=/usr/bin/php-cgi 1> out.log 2> err.log & echo $! > appengine.pid'

script: vendor/bin/phpunit UnitTest tests/DatastoreTest.php

after_script:
    - bash -c 'cat appengine.pid | xargs kill'
